## Numpy

In [2]:
import numpy as np

### Array creation

<img src = './array_creation_np.jpg'></img>

In [44]:
a = np.array([[1, 2, 3], [4, 5, 6]])
l = np.ones_like(a)
print(l)
o = np.zeros_like(a)
print(o)

[[1 1 1]
 [1 1 1]]
[[0 0 0]
 [0 0 0]]


In [57]:
arr = [1, 2, 4, 5, 10]
np.asarray(arr) is arr

False

In [61]:
np_arr = np.array(arr)
np.asarray(np_arr) is np_arr

True

<H3> np.full() </H3> <br> <b> Make an array that all it items are an specific Value </b>

In [43]:
f1 = np.full((4, 3), 10.2)
print(f1, end = "\n\n")
f2 = np.full((4, 2), [10, 1.2] ,dtype=np.float32)
print(f2, end = "\n\n")
f3 = np.full((4, 3), [[2], [3], [4], [5]])
print(f3, end = "\n\n")

[[10.2 10.2 10.2]
 [10.2 10.2 10.2]
 [10.2 10.2 10.2]
 [10.2 10.2 10.2]]

[[10.   1.2]
 [10.   1.2]
 [10.   1.2]
 [10.   1.2]]

[[2 2 2]
 [3 3 3]
 [4 4 4]
 [5 5 5]]



<H3>type casting</H3>

In [79]:
a_range32 = np.arange(15, dtype = 'f4')
a_range64 = a_range.astype('f8')
print(a_range32.dtype, a_range64.dtype)

float32 float64


In [ ]:
Arithemtic 